-- CASSANDRA AI — Supabase DB 스키마 (인증 전용)
-- Supabase는 회원가입·로그인·이메일 인증만 담당
-- 모든 비즈니스 데이터는 Neon DB(Prisma)에 저장
-- 
-- Supabase가 auth.users, auth.sessions, auth.refresh_tokens 등을 자동 관리하므로
-- 별도 테이블 생성 불필요.
--
-- 실행: Supabase 대시보드 → SQL Editor → 복사/붙여넣기 → Run (선택사항)

-- 이메일 인증 설정 (Supabase 대시보드에서도 가능)
-- Authentication → Providers → Email → Confirm email: ON
